// AI Learning Path Finder — Course Data
// To add or update a resource, edit this file and commit.
// See README.md for field documentation.

window.COURSES = [

  // ─── Microsoft Learn · Copilot ───────────────────────────────────────────

  {
    id: "ms-copilot-intro",
    title: "Introduction to Microsoft 365 Copilot",
    provider: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/training/modules/introduction-microsoft-365-copilot/",
    description: "Get a focused orientation to what Copilot is, how it works across M365 apps, and how to use it responsibly — no prerequisites, no license required.",
    levels: ["beginner"],
    roles: ["all"],
    tools: ["copilot"],
    time: "quick",
    duration: "20 min",
    format: "course",
    free: true,
    licenseNote: "",
    pathPosition: 1,
    pathGroup: "copilot-beginner",
  },
  {
    id: "ms-copilot-get-started",
    title: "Get Started with Microsoft 365 Copilot",
    provider: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/training/paths/get-started-with-microsoft-365-copilot/",
    description: "Three-module path covering Copilot across Word, Outlook, Teams, PowerPoint, and OneNote — designed for all professionals with no prior AI experience.",
    levels: ["beginner"],
    roles: ["all"],
    tools: ["copilot"],
    time: "quick",
    duration: "40 min",
    format: "learning-path",
    free: true,
    licenseNote: "",
    pathPosition: 2,
    pathGroup: "copilot-beginner",
  },
  {
    id: "ms-copilot-chat-basic",
    title: "Transform Ideas into Action with Copilot Chat",
    provider: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/training/paths/explore-microsoft-365-copilot-business-chat/",
    description: "Learn to write effective prompts and work smarter with Copilot Chat (Basic) — the free AI assistant available to every Microsoft 365 user without a paid Copilot subscription.",
    levels: ["beginner"],
    roles: ["all"],
    tools: ["copilot"],
    time: "quick",
    duration: "45 min",
    format: "learning-path",
    free: true,
    licenseNote: "Uses Copilot Chat (Basic) — free tier, no paid Copilot license required.",
    pathPosition: 3,
    pathGroup: "copilot-beginner",
  },
  {
    id: "ms-copilot-finance",
    title: "Empower Your Workforce — Copilot for Finance",
    provider: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/training/modules/empower-workforce-copilot-finance/",
    description: "Work through 8 real finance scenarios: Excel modeling, acquisition analysis via Copilot Chat, What-if scenarios, vendor contract review, and executive presentation creation.",
    levels: ["beginner"],
    roles: ["investment", "finance-accounting"],
    tools: ["copilot"],
    time: "quick",
    duration: "1 hr",
    format: "course",
    free: true,
    licenseNote: "Conceptual content is free. Hands-on lab exercises require a paid M365 Copilot license.",
    pathPosition: 1,
    pathGroup: "investment-copilot",
  },
  {
    id: "ms-copilot-use-cases",
    title: "Empower Your Workforce — All Copilot Use Cases",
    provider: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/training/paths/empower-workforce-copilot-use-cases/",
    description: "10-module path with role-specific Copilot workflows for Executives, Finance, HR, Sales, Operations, Legal, and more — the most comprehensive free Copilot training available.",
    levels: ["beginner"],
    roles: ["all"],
    tools: ["copilot"],
    time: "half-day",
    duration: "3 hrs",
    format: "learning-path",
    free: true,
    licenseNote: "Conceptual content is free. Hands-on lab exercises require a paid M365 Copilot license.",
    pathPosition: 1,
    pathGroup: "copilot-intermediate",
  },
  {
    id: "ms-ai-finance-leaders",
    title: "AI for Financial Industry Leaders",
    provider: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/training/paths/discover-microsoft-ai-leaders-financial-industry/",
    description: "Explore how AI is transforming investment analysis, financial planning, and reporting — with Microsoft tools at the center. No license required.",
    levels: ["intermediate"],
    roles: ["investment", "finance-accounting", "strategy-compliance"],
    tools: ["copilot"],
    time: "half-day",
    duration: "2 hrs",
    format: "learning-path",
    free: true,
    licenseNote: "",
    pathPosition: 2,
    pathGroup: "investment-copilot",
  },

  // ─── OpenAI Academy · ChatGPT ────────────────────────────────────────────

  {
    id: "openai-foundations",
    title: "AI Foundations",
    provider: "OpenAI Academy",
    url: "https://academy.openai.com/",
    description: "Start from zero: understand large language models, write clear instructions, and apply ChatGPT to everyday tasks like drafting, summarizing, planning, and meeting prep.",
    levels: ["beginner"],
    roles: ["all"],
    tools: ["chatgpt"],
    time: "half-day",
    duration: "~2 hrs",
    format: "course",
    free: true,
    licenseNote: "Free access — availability may vary by region during ongoing rollout.",
    pathPosition: 1,
    pathGroup: "chatgpt-beginner",
  },
  {
    id: "openai-applied",
    title: "Applied AI Foundations",
    provider: "OpenAI Academy",
    url: "https://academy.openai.com/",
    description: "Build on the basics: apply ChatGPT to more complex work tasks using structured prompting techniques and real workflow examples.",
    levels: ["intermediate"],
    roles: ["all"],
    tools: ["chatgpt"],
    time: "half-day",
    duration: "~2 hrs",
    format: "course",
    free: true,
    licenseNote: "Free access — availability may vary by region during ongoing rollout.",
    pathPosition: 2,
    pathGroup: "chatgpt-beginner",
  },
  {
    id: "openai-agents",
    title: "Agents and Workflows",
    provider: "OpenAI Academy",
    url: "https://academy.openai.com/",
    description: "Design AI-powered workflows and understand agent-based automation — for those ready to move beyond basic prompting into systematic process improvement.",
    levels: ["advanced"],
    roles: ["ops-admin", "strategy-compliance"],
    tools: ["chatgpt"],
    time: "half-day",
    duration: "~2 hrs",
    format: "course",
    free: true,
    licenseNote: "Free access — availability may vary by region during ongoing rollout.",
    pathPosition: 3,
    pathGroup: "chatgpt-beginner",
  },

  // ─── DeepLearning.AI · All Tools ─────────────────────────────────────────

  {
    id: "dlai-gen-ai-everyone",
    title: "Generative AI for Everyone",
    provider: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/courses/generative-ai-for-everyone",
    description: "Andrew Ng's 5-hour vendor-neutral primer: how generative AI works, where it creates business value, and how to think clearly about its limitations — no coding required.",
    levels: ["beginner"],
    roles: ["all"],
    tools: ["all"],
    time: "multi-day",
    duration: "5 hrs",
    format: "course",
    free: true,
    licenseNote: "Video content is free. Graded assignments and certificate require a paid Pro membership.",
    pathPosition: 1,
    pathGroup: "ai-foundations",
  },

  // ─── Anthropic Academy · Claude ──────────────────────────────────────────

  {
    id: "anthropic-claude-101",
    title: "Claude 101",
    provider: "Anthropic Academy",
    url: "https://anthropic.skilljar.com/claude-101",
    description: "Get started with Claude for everyday work tasks — no technical background needed. Certificate awarded on completion.",
    levels: ["beginner"],
    roles: ["all"],
    tools: ["claude"],
    time: "quick",
    duration: "~1 hr",
    format: "course",
    free: true,
    licenseNote: "",
    pathPosition: 1,
    pathGroup: "claude-beginner",
  },
  {
    id: "anthropic-claude-for-work",
    title: "Claude for Work",
    provider: "Anthropic Academy",
    url: "https://www.anthropic.com/learn/claude-for-work",
    description: "Learn to use Claude for team productivity: covers Projects, Artifacts, and role-specific use cases for HR, Sales, Marketing, Operations, and Engineering.",
    levels: ["beginner"],
    roles: ["all"],
    tools: ["claude"],
    time: "half-day",
    duration: "~2 hrs",
    format: "learning-path",
    free: true,
    licenseNote: "",
    pathPosition: 2,
    pathGroup: "claude-beginner",
  },
  {
    id: "anthropic-academy-full",
    title: "Anthropic Academy — Full Library",
    provider: "Anthropic Academy",
    url: "https://www.anthropic.com/learn",
    description: "Browse all 17 free courses across AI Fluency, Claude for Work, API development, and Claude Code — certificates awarded on completion. Launched March 2026.",
    levels: ["beginner", "intermediate", "advanced"],
    roles: ["all"],
    tools: ["claude"],
    time: "multi-day",
    duration: "Varies",
    format: "learning-path",
    free: true,
    licenseNote: "",
    pathPosition: null,
    pathGroup: "",
  },

  // ─── CRE & Financial Modeling · Investment Specialists ───────────────────

  {
    id: "acre-youtube-model",
    title: "AI in Action: Recreating an Excel Financial Model with ChatGPT",
    provider: "Adventures in CRE",
    url: "https://www.youtube.com/watch?v=yP8MvtuPKxs",
    description: "Watch a complete CRE financial model get rebuilt from scratch using ChatGPT Code Interpreter — see exactly where AI accelerates the workflow and where it needs guidance.",
    levels: ["beginner"],
    roles: ["investment", "finance-accounting"],
    tools: ["chatgpt"],
    time: "quick",
    duration: "~20 min",
    format: "video",
    free: true,
    licenseNote: "",
    pathPosition: 1,
    pathGroup: "investment-deep-dive",
  },
  {
    id: "acre-ai-skills-asset-mgmt",
    title: "A.CRE AI Skills — Real Estate Asset Management Model",
    provider: "Adventures in CRE",
    url: "https://www.adventuresincre.com/ai-skill-real-estate-asset-management-model/",
    description: "Prompt packages paired with a real Excel asset management model — use Claude, ChatGPT, or Gemini to analyze, stress-test, and present portfolio performance.",
    levels: ["intermediate"],
    roles: ["investment"],
    tools: ["all"],
    time: "half-day",
    duration: "Self-paced",
    format: "guide",
    free: true,
    licenseNote: "Pay-what-you're-able pricing — $0 minimum accepted.",
    pathPosition: 2,
    pathGroup: "investment-deep-dive",
  },
  {
    id: "acre-ai-skills-mortgage",
    title: "A.CRE AI Skills — Commercial Mortgage Loan Analysis",
    provider: "Adventures in CRE",
    url: "https://www.adventuresincre.com/ai-skill-commercial-mortgage-loan-analysis-model/",
    description: "Use AI to automate loan sizing, DSCR analysis, debt yield calculations, and LTV screening on a real commercial mortgage model.",
    levels: ["intermediate"],
    roles: ["investment", "finance-accounting"],
    tools: ["all"],
    time: "half-day",
    duration: "Self-paced",
    format: "guide",
    free: true,
    licenseNote: "Pay-what-you're-able pricing — $0 minimum accepted.",
    pathPosition: 3,
    pathGroup: "investment-deep-dive",
  },
  {
    id: "excel-agent-financial-model",
    title: "Excel Agent Mode: Build Financial Models with AI in Minutes",
    provider: "Nicolas Boucher (YouTube)",
    url: "https://www.youtube.com/watch?v=Jts6f78IyM4",
    description: "Full tutorial: use Excel Agent Mode to build a 13-week cash flow forecast and a 5-year 3-statement financial model from scratch with AI.",
    levels: ["intermediate"],
    roles: ["investment", "finance-accounting"],
    tools: ["all"],
    time: "quick",
    duration: "~30 min",
    format: "video",
    free: true,
    licenseNote: "",
    pathPosition: 4,
    pathGroup: "investment-deep-dive",
  },
  {
    id: "cre-agent-skills",
    title: "CRE Agent Skills — 66 AI Prompt Files for CRE",
    provider: "GitHub: ahacker-1",
    url: "https://github.com/ahacker-1/cre-agent-skills",
    description: "Open-source library of 66 ready-to-use AI prompts for CRE professionals: 5-year pro forma, IRR/equity multiple/CoC returns, DSCR, debt sizing, due diligence, and asset management workflows.",
    levels: ["intermediate"],
    roles: ["investment"],
    tools: ["all"],
    time: "quick",
    duration: "Self-paced",
    format: "github-repo",
    free: true,
    licenseNote: "Apache 2.0 open source — free to use and adapt.",
    pathPosition: null,
    pathGroup: "",
  },
  {
    id: "claude-cookbooks-finance",
    title: "Claude Cookbooks — Financial Applications",
    provider: "Anthropic (GitHub)",
    url: "https://github.com/anthropics/claude-cookbooks/blob/main/skills/notebooks/02_skills_financial_applications.ipynb",
    description: "Jupyter notebook showing Claude generating multi-sheet Excel workbooks with portfolio risk metrics (Beta, VaR, Sharpe Ratio, Max Drawdown) and investment committee presentation slides.",
    levels: ["advanced"],
    roles: ["investment", "strategy-compliance"],
    tools: ["claude"],
    time: "half-day",
    duration: "1–2 hrs",
    format: "github-repo",
    free: true,
    licenseNote: "",
    pathPosition: null,
    pathGroup: "",
  },
  {
    id: "acre-prompt-guide",
    title: "AI Prompt Engineering for CRE",
    provider: "Adventures in CRE",
    url: "https://www.adventuresincre.com/ai-cre-prompt-engineering/",
    description: "Practical prompting strategies for commercial real estate — how to frame deal analysis, market research, and underwriting questions to get the best results from any AI tool.",
    levels: ["beginner"],
    roles: ["investment"],
    tools: ["all"],
    time: "quick",
    duration: "~15 min",
    format: "guide",
    free: true,
    licenseNote: "",
    pathPosition: null,
    pathGroup: "",
  },
  {
    id: "cfi-chatgpt-finance-free",
    title: "ChatGPT for Finance — Resource Guide",
    provider: "Corporate Finance Institute",
    url: "https://corporatefinanceinstitute.com/resources/career/chatgpt-for-finance/",
    description: "Free editorial guide from CFI covering how ChatGPT, Claude, and Gemini each apply to financial statement analysis, FP&A, investment analysis, and Excel formula writing.",
    levels: ["beginner"],
    roles: ["investment", "finance-accounting"],
    tools: ["all"],
    time: "quick",
    duration: "~20 min",
    format: "guide",
    free: true,
    licenseNote: "",
    pathPosition: null,
    pathGroup: "",
  },

];
